// <auto-generated />
namespace uStora.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test2018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test2018));
        
        string IMigrationMetadata.Id
        {
            get { return "201812301438053_test2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
